import type {
  User,
  Property,
  Client,
  Appointment,
  DocumentItem,
  ActivityItem,
} from "@/types";

export const mockUsers: User[] = [
  {
    id: "u-1",
    email: "admin@aecrenestates.com",
    firstName: "Sarah",
    lastName: "Mitchell",
    role: "admin",
    phone: "+1 202-555-0100",
    bio: "Founder & CEO of AecrenEstates. 15+ years in real estate.",
    createdAt: "2023-01-15T08:00:00Z",
  },
  {
    id: "u-2",
    email: "agent@aecrenestates.com",
    firstName: "James",
    lastName: "Carter",
    role: "agent",
    phone: "+1 202-555-0101",
    bio: "Senior agent specializing in luxury homes.",
    createdAt: "2023-03-20T08:00:00Z",
  },
  {
    id: "u-3",
    email: "client@aecrenestates.com",
    firstName: "Emily",
    lastName: "Rodriguez",
    role: "client",
    phone: "+1 202-555-0102",
    createdAt: "2024-06-10T08:00:00Z",
  },
];

const houseImg = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=800`;

export const mockProperties: Property[] = [
  {
    id: "p-1",
    title: "Modern Glass Villa with Infinity Pool",
    description:
      "Stunning contemporary villa featuring floor-to-ceiling windows, an infinity pool overlooking the city, and premium finishes throughout. The open-concept living area flows seamlessly into a state-of-the-art kitchen with quartz countertops and custom cabinetry. Master suite with private terrace and spa-like en-suite bathroom.",
    price: 1_850_000,
    type: "house",
    listingType: "sale",
    status: "available",
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    location: "Beverly Hills, CA",
    city: "Beverly Hills",
    neighborhood: "Trousdale",
    lat: 34.0901,
    lng: -118.4035,
    images: [
      houseImg(1396122),
      houseImg(1571460),
      houseImg(2029722),
      houseImg(323780),
    ],
    amenities: {
      parking: true,
      pool: true,
      gym: true,
      garden: true,
      security: true,
      elevator: false,
      furnished: true,
      petFriendly: true,
      airConditioning: true,
      laundry: true,
    },
    agentId: "u-2",
    createdAt: "2024-09-15T10:00:00Z",
    updatedAt: "2024-10-01T14:30:00Z",
    featured: true,
    views: 1240,
  },
  {
    id: "p-2",
    title: "Downtown Luxury Penthouse",
    description:
      "Exquisite penthouse apartment in the heart of downtown with panoramic city views. Features include a private rooftop terrace, smart home automation, and access to building amenities including rooftop pool, fitness center, and 24/7 concierge.",
    price: 12_000,
    type: "apartment",
    listingType: "rent",
    status: "available",
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    location: "Miami, FL",
    city: "Miami",
    neighborhood: "Brickell",
    lat: 25.7617,
    lng: -80.1918,
    images: [
      houseImg(758699),
      houseImg(3209011),
      houseImg(1457847),
    ],
    amenities: {
      parking: true,
      pool: true,
      gym: true,
      garden: false,
      security: true,
      elevator: true,
      furnished: true,
      petFriendly: false,
      airConditioning: true,
      laundry: true,
    },
    agentId: "u-2",
    createdAt: "2024-09-20T10:00:00Z",
    updatedAt: "2024-09-28T09:15:00Z",
    featured: true,
    views: 890,
  },
  {
    id: "p-3",
    title: "Charming Brownstone in Historic District",
    description:
      "Beautifully restored 19th-century brownstone with original hardwood floors, crown molding, and a private garden. Four levels of living space including a finished basement. Walking distance to parks, cafes, and top-rated schools.",
    price: 925_000,
    type: "townhouse",
    listingType: "sale",
    status: "under_offer",
    bedrooms: 4,
    bathrooms: 3,
    area: 3100,
    location: "Boston, MA",
    city: "Boston",
    neighborhood: "Back Bay",
    lat: 42.3505,
    lng: -71.0813,
    images: [
      houseImg(1438832),
      houseImg(259588),
      houseImg(1396122),
    ],
    amenities: {
      parking: false,
      pool: false,
      gym: false,
      garden: true,
      security: true,
      elevator: false,
      furnished: false,
      petFriendly: true,
      airConditioning: true,
      laundry: true,
    },
    agentId: "u-2",
    createdAt: "2024-08-10T10:00:00Z",
    updatedAt: "2024-09-25T16:00:00Z",
    featured: true,
    views: 670,
  },
  {
    id: "p-4",
    title: "Waterfront Condo with Marina Access",
    description:
      "Spectacular waterfront condominium with direct marina access and unobstructed ocean views. Features a modern kitchen, spacious living areas, and a large balcony perfect for entertaining. Building offers resort-style amenities.",
    price: 650_000,
    type: "condo",
    listingType: "sale",
    status: "available",
    bedrooms: 2,
    bathrooms: 2,
    area: 1450,
    location: "San Diego, CA",
    city: "San Diego",
    neighborhood: "Coronado",
    lat: 32.7157,
    lng: -117.1611,
    images: [
      houseImg(271624),
      houseImg(2029698),
      houseImg(1438832),
    ],
    amenities: {
      parking: true,
      pool: true,
      gym: true,
      garden: false,
      security: true,
      elevator: true,
      furnished: false,
      petFriendly: true,
      airConditioning: true,
      laundry: true,
    },
    agentId: "u-2",
    createdAt: "2024-09-05T10:00:00Z",
    updatedAt: "2024-09-20T11:00:00Z",
    featured: false,
    views: 420,
  },
  {
    id: "p-5",
    title: "Spacious Family Home with Large Backyard",
    description:
      "Perfect family home in a quiet suburban neighborhood. Features include a renovated kitchen, hardwood floors throughout, a finished basement, and a beautifully landscaped backyard with a patio area. Close to top-rated schools and parks.",
    price: 545_000,
    type: "house",
    listingType: "sale",
    status: "sold",
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    location: "Austin, TX",
    city: "Austin",
    neighborhood: "Round Rock",
    lat: 30.2672,
    lng: -97.7431,
    images: [
      houseImg(271639),
      houseImg(1111360),
      houseImg(1396122),
    ],
    amenities: {
      parking: true,
      pool: false,
      gym: false,
      garden: true,
      security: false,
      elevator: false,
      furnished: false,
      petFriendly: true,
      airConditioning: true,
      laundry: true,
    },
    agentId: "u-2",
    createdAt: "2024-07-01T10:00:00Z",
    updatedAt: "2024-09-10T08:00:00Z",
    featured: false,
    views: 2100,
  },
  {
    id: "p-6",
    title: "Modern Studio in Tech Hub",
    description:
      "Sleek studio apartment in the heart of the tech district. Open floor plan with high ceilings, stainless steel appliances, and in-unit laundry. Building features a rooftop lounge, fitness center, and bike storage.",
    price: 3_200,
    type: "apartment",
    listingType: "rent",
    status: "rented",
    bedrooms: 1,
    bathrooms: 1,
    area: 650,
    location: "San Francisco, CA",
    city: "San Francisco",
    neighborhood: "SoMa",
    lat: 37.7749,
    lng: -122.4194,
    images: [
      houseImg(1571460),
      houseImg(3209011),
    ],
    amenities: {
      parking: false,
      pool: false,
      gym: true,
      garden: false,
      security: true,
      elevator: true,
      furnished: true,
      petFriendly: false,
      airConditioning: true,
      laundry: true,
    },
    agentId: "u-2",
    createdAt: "2024-06-15T10:00:00Z",
    updatedAt: "2024-08-20T08:00:00Z",
    featured: false,
    views: 540,
  },
  {
    id: "p-7",
    title: "Prime Commercial Space on Main Street",
    description:
      "High-visibility commercial space on a busy main street. Formerly a boutique retail store. Large display windows, high ceilings, and a flexible open floor plan. Ample parking in the rear.",
    price: 4_500,
    type: "commercial",
    listingType: "rent",
    status: "available",
    bedrooms: 0,
    bathrooms: 1,
    area: 2200,
    location: "Denver, CO",
    city: "Denver",
    neighborhood: "LoDo",
    lat: 39.7392,
    lng: -104.9903,
    images: [
      houseImg(323780),
      houseImg(259588),
    ],
    amenities: {
      parking: true,
      pool: false,
      gym: false,
      garden: false,
      security: true,
      elevator: false,
      furnished: false,
      petFriendly: false,
      airConditioning: true,
      laundry: false,
    },
    agentId: "u-2",
    createdAt: "2024-09-28T10:00:00Z",
    updatedAt: "2024-10-01T09:00:00Z",
    featured: false,
    views: 180,
  },
  {
    id: "p-8",
    title: "Vacant Land for Development",
    description:
      "5-acre parcel of land zoned for residential development. Flat terrain with utilities at the street. Excellent opportunity for builders and developers. Surrounded by new construction homes.",
    price: 350_000,
    type: "land",
    listingType: "sale",
    status: "draft",
    bedrooms: 0,
    bathrooms: 0,
    area: 217800,
    location: "Phoenix, AZ",
    city: "Phoenix",
    neighborhood: "North Gateway",
    lat: 33.4484,
    lng: -112.074,
    images: [houseImg(2029698)],
    amenities: {
      parking: false,
      pool: false,
      gym: false,
      garden: false,
      security: false,
      elevator: false,
      furnished: false,
      petFriendly: false,
      airConditioning: false,
      laundry: false,
    },
    agentId: "u-2",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
    featured: false,
    views: 45,
  },
];

export const mockClients: Client[] = [
  {
    id: "c-1",
    firstName: "Michael",
    lastName: "Chen",
    email: "mchen@email.com",
    phone: "+1 415-555-0142",
    status: "negotiation",
    budget: 2_000_000,
    preferredLocations: ["Beverly Hills", "Malibu"],
    propertyTypeInterest: ["house"],
    assignedAgentId: "u-2",
    notes: [
      {
        id: "n-1",
        clientId: "c-1",
        content: "Very interested in the Glass Villa. Wants to schedule a second viewing with his architect.",
        authorId: "u-2",
        authorName: "James Carter",
        createdAt: "2024-10-01T14:00:00Z",
      },
    ],
    activities: [
      {
        id: "a-1",
        clientId: "c-1",
        type: "status_change",
        description: "Lead status changed to Negotiation",
        authorName: "James Carter",
        createdAt: "2024-10-01T14:30:00Z",
      },
      {
        id: "a-2",
        clientId: "c-1",
        type: "viewing",
        description: "Viewed 'Modern Glass Villa with Infinity Pool'",
        authorName: "James Carter",
        createdAt: "2024-09-28T11:00:00Z",
      },
      {
        id: "a-3",
        clientId: "c-1",
        type: "call",
        description: "Initial phone call — discussed budget and preferences",
        authorName: "James Carter",
        createdAt: "2024-09-25T09:00:00Z",
      },
      {
        id: "a-4",
        clientId: "c-1",
        type: "created",
        description: "Lead created from website inquiry form",
        authorName: "System",
        createdAt: "2024-09-24T16:00:00Z",
      },
    ],
    interestedPropertyIds: ["p-1"],
    createdAt: "2024-09-24T16:00:00Z",
    updatedAt: "2024-10-01T14:30:00Z",
  },
  {
    id: "c-2",
    firstName: "Jessica",
    lastName: "Thompson",
    email: "jthompson@email.com",
    phone: "+1 617-555-0198",
    status: "viewing",
    budget: 950_000,
    preferredLocations: ["Boston"],
    propertyTypeInterest: ["townhouse"],
    assignedAgentId: "u-2",
    notes: [
      {
        id: "n-2",
        clientId: "c-2",
        content: "Loves the Back Bay brownstone. Currently comparing with two other properties.",
        authorId: "u-2",
        authorName: "James Carter",
        createdAt: "2024-09-29T10:00:00Z",
      },
    ],
    activities: [
      {
        id: "a-5",
        clientId: "c-2",
        type: "viewing",
        description: "Viewed 'Charming Brownstone in Historic District'",
        authorName: "James Carter",
        createdAt: "2024-09-29T10:30:00Z",
      },
      {
        id: "a-6",
        clientId: "c-2",
        type: "email",
        description: "Sent property details and comparison sheet",
        authorName: "James Carter",
        createdAt: "2024-09-26T14:00:00Z",
      },
      {
        id: "a-7",
        clientId: "c-2",
        type: "created",
        description: "Lead created from referral",
        authorName: "Sarah Mitchell",
        createdAt: "2024-09-20T12:00:00Z",
      },
    ],
    interestedPropertyIds: ["p-3"],
    createdAt: "2024-09-20T12:00:00Z",
    updatedAt: "2024-09-29T10:00:00Z",
  },
  {
    id: "c-3",
    firstName: "Robert",
    lastName: "Williams",
    email: "rwilliams@email.com",
    phone: "+1 305-555-0167",
    status: "new",
    budget: 15_000,
    preferredLocations: ["Miami"],
    propertyTypeInterest: ["apartment"],
    assignedAgentId: "u-2",
    notes: [],
    activities: [
      {
        id: "a-8",
        clientId: "c-3",
        type: "created",
        description: "Lead created from property inquiry on Downtown Luxury Penthouse",
        authorName: "System",
        createdAt: "2024-10-02T09:00:00Z",
      },
    ],
    interestedPropertyIds: ["p-2"],
    createdAt: "2024-10-02T09:00:00Z",
    updatedAt: "2024-10-02T09:00:00Z",
  },
  {
    id: "c-4",
    firstName: "Linda",
    lastName: "Garcia",
    email: "lgarcia@email.com",
    phone: "+1 619-555-0112",
    status: "contacted",
    budget: 700_000,
    preferredLocations: ["San Diego"],
    propertyTypeInterest: ["condo"],
    assignedAgentId: "u-2",
    notes: [
      {
        id: "n-3",
        clientId: "c-4",
        content: "Pre-approved for mortgage. Ready to move quickly on the right property.",
        authorId: "u-2",
        authorName: "James Carter",
        createdAt: "2024-09-30T15:00:00Z",
      },
    ],
    activities: [
      {
        id: "a-9",
        clientId: "c-4",
        type: "call",
        description: "Discussed financing options and timeline",
        authorName: "James Carter",
        createdAt: "2024-09-30T15:30:00Z",
      },
      {
        id: "a-10",
        clientId: "c-4",
        type: "created",
        description: "Lead created from open house sign-in",
        authorName: "James Carter",
        createdAt: "2024-09-27T14:00:00Z",
      },
    ],
    interestedPropertyIds: ["p-4"],
    createdAt: "2024-09-27T14:00:00Z",
    updatedAt: "2024-09-30T15:00:00Z",
  },
  {
    id: "c-5",
    firstName: "David",
    lastName: "Kim",
    email: "dkim@email.com",
    phone: "+1 512-555-0183",
    status: "closed",
    budget: 550_000,
    preferredLocations: ["Austin"],
    propertyTypeInterest: ["house"],
    assignedAgentId: "u-2",
    notes: [
      {
        id: "n-4",
        clientId: "c-5",
        content: "Deal closed successfully. Client very happy with their new home.",
        authorId: "u-2",
        authorName: "James Carter",
        createdAt: "2024-09-10T10:00:00Z",
      },
    ],
    activities: [
      {
        id: "a-11",
        clientId: "c-5",
        type: "status_change",
        description: "Deal closed — property sold for $545,000",
        authorName: "James Carter",
        createdAt: "2024-09-10T10:00:00Z",
      },
      {
        id: "a-12",
        clientId: "c-5",
        type: "viewing",
        description: "Final walkthrough completed",
        authorName: "James Carter",
        createdAt: "2024-09-05T11:00:00Z",
      },
    ],
    interestedPropertyIds: ["p-5"],
    createdAt: "2024-07-15T12:00:00Z",
    updatedAt: "2024-09-10T10:00:00Z",
  },
  {
    id: "c-6",
    firstName: "Amanda",
    lastName: "Foster",
    email: "afoster@email.com",
    phone: "+1 415-555-0199",
    status: "lost",
    budget: 4_000,
    preferredLocations: ["San Francisco"],
    propertyTypeInterest: ["apartment"],
    assignedAgentId: "u-2",
    notes: [
      {
        id: "n-5",
        clientId: "c-6",
        content: "Decided to go with another agency. Budget was below our minimums.",
        authorId: "u-2",
        authorName: "James Carter",
        createdAt: "2024-08-25T14:00:00Z",
      },
    ],
    activities: [
      {
        id: "a-13",
        clientId: "c-6",
        type: "status_change",
        description: "Lead marked as Lost — went with competitor",
        authorName: "James Carter",
        createdAt: "2024-08-25T14:00:00Z",
      },
    ],
    interestedPropertyIds: ["p-6"],
    createdAt: "2024-07-20T12:00:00Z",
    updatedAt: "2024-08-25T14:00:00Z",
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "ap-1",
    propertyId: "p-1",
    propertyTitle: "Modern Glass Villa with Infinity Pool",
    propertyImage: houseImg(1396122),
    clientId: "c-1",
    clientName: "Michael Chen",
    agentId: "u-2",
    agentName: "James Carter",
    date: "2024-10-10",
    time: "10:00",
    duration: 60,
    status: "scheduled",
    notes: "Second viewing with client's architect for renovation assessment.",
    createdAt: "2024-10-01T14:30:00Z",
  },
  {
    id: "ap-2",
    propertyId: "p-2",
    propertyTitle: "Downtown Luxury Penthouse",
    propertyImage: houseImg(758699),
    clientId: "c-3",
    clientName: "Robert Williams",
    agentId: "u-2",
    agentName: "James Carter",
    date: "2024-10-11",
    time: "14:00",
    duration: 45,
    status: "scheduled",
    createdAt: "2024-10-02T09:00:00Z",
  },
  {
    id: "ap-3",
    propertyId: "p-4",
    propertyTitle: "Waterfront Condo with Marina Access",
    propertyImage: houseImg(271624),
    clientId: "c-4",
    clientName: "Linda Garcia",
    agentId: "u-2",
    agentName: "James Carter",
    date: "2024-10-09",
    time: "15:30",
    duration: 60,
    status: "scheduled",
    notes: "Client is pre-approved, this may be the final viewing before offer.",
    createdAt: "2024-09-30T16:00:00Z",
  },
  {
    id: "ap-4",
    propertyId: "p-3",
    propertyTitle: "Charming Brownstone in Historic District",
    propertyImage: houseImg(1438832),
    clientId: "c-2",
    clientName: "Jessica Thompson",
    agentId: "u-2",
    agentName: "James Carter",
    date: "2024-09-29",
    time: "10:30",
    duration: 60,
    status: "completed",
    createdAt: "2024-09-26T14:00:00Z",
  },
  {
    id: "ap-5",
    propertyId: "p-5",
    propertyTitle: "Spacious Family Home with Large Backyard",
    propertyImage: houseImg(271639),
    clientId: "c-5",
    clientName: "David Kim",
    agentId: "u-2",
    agentName: "James Carter",
    date: "2024-09-05",
    time: "11:00",
    duration: 45,
    status: "completed",
    createdAt: "2024-09-01T10:00:00Z",
  },
  {
    id: "ap-6",
    propertyId: "p-2",
    propertyTitle: "Downtown Luxury Penthouse",
    propertyImage: houseImg(758699),
    clientId: "c-3",
    clientName: "Robert Williams",
    agentId: "u-2",
    agentName: "James Carter",
    date: "2024-10-05",
    time: "13:00",
    duration: 30,
    status: "cancelled",
    notes: "Client rescheduled due to work conflict.",
    createdAt: "2024-10-03T08:00:00Z",
  },
];

export const mockDocuments: DocumentItem[] = [
  {
    id: "d-1",
    name: "Purchase Agreement - Chen.pdf",
    type: "contract",
    fileType: "pdf",
    size: 245_000,
    url: "#",
    propertyId: "p-1",
    clientId: "c-1",
    uploadedById: "u-2",
    uploadedByName: "James Carter",
    createdAt: "2024-10-01T15:00:00Z",
  },
  {
    id: "d-2",
    name: "Property Inspection Report.pdf",
    type: "inspection",
    fileType: "pdf",
    size: 1_200_000,
    url: "#",
    propertyId: "p-3",
    uploadedById: "u-2",
    uploadedByName: "James Carter",
    createdAt: "2024-09-27T10:00:00Z",
  },
  {
    id: "d-3",
    name: "Client ID - Garcia.jpg",
    type: "id",
    fileType: "jpg",
    size: 890_000,
    url: "#",
    clientId: "c-4",
    uploadedById: "u-2",
    uploadedByName: "James Carter",
    createdAt: "2024-09-28T12:00:00Z",
  },
  {
    id: "d-4",
    name: "Offer Letter - Thompson.pdf",
    type: "offer",
    fileType: "pdf",
    size: 180_000,
    url: "#",
    propertyId: "p-3",
    clientId: "c-2",
    uploadedById: "u-2",
    uploadedByName: "James Carter",
    createdAt: "2024-09-29T14:00:00Z",
  },
  {
    id: "d-5",
    name: "Closing Statement - Kim.pdf",
    type: "contract",
    fileType: "pdf",
    size: 320_000,
    url: "#",
    propertyId: "p-5",
    clientId: "c-5",
    uploadedById: "u-2",
    uploadedByName: "James Carter",
    createdAt: "2024-09-10T11:00:00Z",
  },
];

export const mockRecentActivity: ActivityItem[] = [
  {
    id: "ra-1",
    type: "deal",
    description: "Negotiation started for 'Modern Glass Villa with Infinity Pool'",
    actorName: "James Carter",
    createdAt: "2024-10-01T14:30:00Z",
  },
  {
    id: "ra-2",
    type: "property",
    description: "New listing created: 'Prime Commercial Space on Main Street'",
    actorName: "James Carter",
    createdAt: "2024-09-28T10:00:00Z",
  },
  {
    id: "ra-3",
    type: "appointment",
    description: "Viewing scheduled with Michael Chen for Oct 10",
    actorName: "James Carter",
    createdAt: "2024-10-01T14:31:00Z",
  },
  {
    id: "ra-4",
    type: "client",
    description: "New lead: Robert Williams from website inquiry",
    actorName: "System",
    createdAt: "2024-10-02T09:00:00Z",
  },
  {
    id: "ra-5",
    type: "deal",
    description: "Deal closed — 'Spacious Family Home' sold for $545K",
    actorName: "James Carter",
    createdAt: "2024-09-10T10:00:00Z",
  },
  {
    id: "ra-6",
    type: "document",
    description: "Purchase agreement uploaded for Michael Chen",
    actorName: "James Carter",
    createdAt: "2024-10-01T15:00:00Z",
  },
];
